### ISSUE TITLE
[1.18.2] Missing DUMP argument

### ISSUE THREAD

**Issue by itsdinkd** [Prunoideae/ProbeJS#13]
probejs-4.0.0-fix3-forge.jar

![image](https://user-images.githubusercontent.com/35115304/210182228-cfcd36ff-1497-4d49-88da-a5892b56c3b4.png)

**Comment by Prunoideae** [comment]
Are you in a multiplayer world? Dumping in multiplayer world is intentionally disabled because ProbeJS needs to access a lot of server-side classes to generate a dump (which can be risky for the server), and the dump will possibly be generated on the server folder, so it means that client-side classes will not be dumped (like ClientEvents) if it's running in multiplayer world.

Also it requires you to have cheat enabled in single player world, so most player won't ever see it if they don't have it enabled.

**Comment by itsdinkd** [comment]
Single player. and im pretty sure i was in creative as I enter creative immediately when I join my worlds to work on my pack

**Comment by Prunoideae** [comment]
This is weird, can't reproduce on my client at all.
