### ISSUE TITLE
[1.19.2 Suggestion] Support for Loot Tables

### ISSUE THREAD

**Issue by itsdinkd** [Prunoideae/ProbeJS#19]
So we have tag support, regular item / entity support, can you add Loot Table support? 

ex; `@minecraft.loot_tables.entities.creeper`
ex: `@minecraft.loot_tables.chests.village.villager_plain_house`

**Comment by Prunoideae** [comment]
For config editing? I think it will come in one or two versions, the snippets dump might get a somewhat rewrite, too.

**Comment by Prunoideae** [comment]
Just rewrote the snippet generation to make it way clearer and more powerful than before. Also, the support for loot tables is added. Have snippets for mod ids too.

![image](https://user-images.githubusercontent.com/24620047/230418146-d9032786-007a-4735-a75b-1c432f602c5a.png)

![image](https://user-images.githubusercontent.com/24620047/230422035-9f09308c-e3e0-4e05-a537-8424f916bf3c.png)


This will be released together with other modifications when a newer version of KubeJS is out (because it contains a lot of features which will break ProbeJS)

**Comment by itsdinkd** [comment]
Awesome ^^

Thank you <3
