### ISSUE TITLE
Probe not generating autocompletion; error in latest.log

### ISSUE THREAD

**Issue by Druivenpasta** [Prunoideae/ProbeJS#76]
Currently using Probejs 7.0.0 on 1.20.1 with forge 47.1.3. 
[latest.log](https://github.com/user-attachments/files/15995165/latest.log)
Here is my log: on line 3974 one can see that I dumped, but a stacktrace showed up.
This was after I did a shitton of investigating as I am already trying for one hour to get a casting json that I cant be asked to find in the jar. I hope this has a quick fix :) (note: recipe json generation in settings is enabled)

**Comment by Toastunn** [comment]
i have this same error in my logs on version 7.0.1 on forge 47.2.20
[latest.log](https://github.com/user-attachments/files/16005552/latest.log)

**Comment by Prunoideae** [comment]
If you found there are `.d.ts` files generated in the `.minecraft/.probe` folder, then the generation is successful, I can't suppress errors that is not from my code.

@Toastunn You are using the version 5.9.3, the rewritten ProbeJS does not download docs from the remote server anymore.

**Comment by Druivenpasta** [comment]
They have in fact been generated, got any idea why there is no autocompletion? Thank you for your time

**Comment by Prunoideae** [comment]
Did you place your script files in the `src/` folder? 1.20.1 requires you to do so to get completions; this is fixed in 1.21.

Otherwise, it might be possible that you have too many mods, like ~10k item entries, which will effectively stop the completion due to some problem in VSCode; this is also fixed in 1.21.

**Comment by Druivenpasta** [comment]
![image](https://github.com/Prunoideae/ProbeJS/assets/94719433/9d46d5e3-436d-4661-9d50-5b171e548fda)
I moved them over a few days ago when that was mentioned on the curseforge page, I am currently running 131 mods, which sounds acceptable. It doesn't even have Gregtech with it's boatload of items...

**Comment by Prunoideae** [comment]
Hmm, why you have 2 `jsconfig.json` at different places? That would cause a project conflict, and I guess the inner `jsconfig.json` is the generated by ProbeJS too? So it is highly likely that it pointed to invalid type locations (due to using relative paths) and overrides the outer `jsconfig.json`.

**Comment by Druivenpasta** [comment]
Forgor, was probably copied when moving over my files to `src/`, I'll see what happens when I remove it, I'll be sure to close this issue when it works!

**Comment by Druivenpasta** [comment]
Uhhhh, now I have no autocompletion at all, even for events that I've already written in the same file? I booted up the instance, logged in and dumped again.

**Comment by Prunoideae** [comment]
Weird... And does your `jsconfig.json` still error? 

Anyway, you might refer to https://github.com/Prunoideae/ProbeJS/blob/1.21/docs/installation-and-usage/page.md to see if it works

**Comment by Druivenpasta** [comment]
I went through the setup and it checks out, also made sure there was nothing outside the source folder besides jsconfig.json. I got my completions for kube functions back, and I can import classes now. Still no recipe or item completions though.

**Comment by Prunoideae** [comment]
No recipes or item completions can be due to the performance problem of VSCode on some very complex type solving (which should be fixed on 1.21), you can try to delete all `registry_type.d.ts` in the `global` of `server`, `client`, and `startup` folder in `.probe` and see if recipe completion is back, then use `@item` snippet as a substitution for item completions.

**Comment by Druivenpasta** [comment]
I have removed all three, but I am afraid nothing has changed, I don't see jsons appear when typing # nor do I see a lowercase `item` when typing that.

**Comment by Prunoideae** [comment]
Recipe json for `#` is long gone... I should update the docs more often. `item` is triggered by typing `@`, `#` is for other items.

**Comment by Druivenpasta** [comment]
Guess I am an OG prober XD, what is the prefix for triggering recipes, if there even is one?

**Comment by Prunoideae** [comment]
There isn't, but you can get recipe completions in the ServerEvents.recipes(event=> ...) because that is specially typed.
