### ISSUE TITLE
Failed to load the VSCode extension

### ISSUE THREAD

**Issue by ghost** [Prunoideae/ProbeJS#85]
Failed to load in VSCode with code:
ProbeJS WebSocket connection failed:AggregateError
![Uploading 屏幕截图 2024-07-14 234928.png…]()

**Comment by Prunoideae** [comment]
You need to open the VSCode when the Minecraft is running and you're in world, or reconnect when you entered the world.

**Comment by kingqaquuu** [comment]
Did you fix that? I had that problem too, I don't know how to fix that, I ran ProbeJS on two machines,both of them have this problem

**Comment by yuejiewudi1997** [comment]
> You need to open the VSCode when the Minecraft is running and you're in world, or reconnect when you entered the world.

Still not working.

**Comment by ghost** [comment]
> You need to open the VSCode when the Minecraft is running and you're in world, or reconnect when you entered the world.
I have restarted VSCode several times while the game is running, but it still hasn't been resolved.Should I lauch the minecraft with d official laucher?

**Comment by Prunoideae** [comment]
It will not work on any Minecraft version that is not 1.21

**Comment by ghost** [comment]
> It will not work on any Minecraft version that is not 1.21

so it won't run on 1.20.1?

**Comment by Prunoideae** [comment]
Yes

**Comment by ghost** [comment]
> Yes

but my modpack is still on 1.20,and it's unlikely to upgrade in the near future.how can I use it

**Comment by Prunoideae** [comment]
The answer is you can't use it, or you can try to make a pull request to update all the 1.21 features back to 1.20.1.

**Comment by CauaTheKing** [comment]
> The answer is you can't use it, or you can try to make a pull request to update all the 1.21 features back to 1.20.1.

That's weird for me because the error happens with i using 1.20.1, maybe due to be using Forge?
PS: had the same problem in this issue.

**Comment by PINPAL** [comment]
So ProbeJS is not compatible with anything pre-1.21 anymore? Seems like a major oversight?

**Comment by ScoutTheSaneless** [comment]
yeah...that's a HUGE problem...

**Comment by Prunoideae** [comment]
> So ProbeJS is not compatible with anything pre-1.21 anymore? Seems like a major oversight?



> yeah...that's a HUGE problem...


In pre-1.21 versions ProbeJS runs without needing the extension, most of the functionalities are in the generated JS dump files. It will work if you don't have mods installed that would cause random mixin problems when ProbeJS dumps the type.

I'm unable to maintain the older codebase because there're at least 2 rewrites for ProbeJS just because how the code is changed from KJS 1.20.1 to KJS 1.21, and from Forge to Neoforge. Every time the mod is updated it introduces tons of breaking change and internal stuffs that I must handle, and till now there are still like one big system incoming for KubeJS 7.2 even after I already rewrote like 2 or 3, and 7.2 is just a MINOR version that is not in a large version number diff???
